# ============================================================================
# FRONTEND API & LAMBDAS
# Complements main-modules.tf by adding the API Gateway for the UI
# ============================================================================

# ============================================================================
# FRONTEND STATIC WEBSITE HOSTING (S3 + CloudFront)
# Cost-efficient solution for up to 50 users
# ============================================================================

# --- S3 Bucket for Frontend ---
resource "aws_s3_bucket" "frontend" {
  bucket        = "${var.project_name}-${var.environment}-frontend-${data.aws_caller_identity.current.account_id}"
  force_destroy = true

  tags = {
    Name = "${var.project_name}-${var.environment}-frontend"
  }
}

resource "aws_s3_bucket_public_access_block" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  block_public_acls       = true
  block_public_policy     = true
  ignore_public_acls      = true
  restrict_public_buckets = true
}

resource "aws_s3_bucket_versioning" "frontend" {
  bucket = aws_s3_bucket.frontend.id
  versioning_configuration {
    status = "Enabled"
  }
}

# --- CloudFront Origin Access Control ---
resource "aws_cloudfront_origin_access_control" "frontend" {
  name                              = "${var.project_name}-${var.environment}-frontend-oac"
  description                       = "OAC for frontend S3 bucket"
  origin_access_control_origin_type = "s3"
  signing_behavior                  = "always"
  signing_protocol                  = "sigv4"
}

# --- CloudFront Distribution ---
resource "aws_cloudfront_distribution" "frontend" {
  enabled             = true
  is_ipv6_enabled     = true
  default_root_object = "index.html"
  price_class         = "PriceClass_100" # US, Canada, Europe only - most cost efficient
  comment             = "${var.project_name} Frontend"

  origin {
    domain_name              = aws_s3_bucket.frontend.bucket_regional_domain_name
    origin_id                = "S3-${aws_s3_bucket.frontend.id}"
    origin_access_control_id = aws_cloudfront_origin_access_control.frontend.id
  }

  default_cache_behavior {
    allowed_methods  = ["GET", "HEAD", "OPTIONS"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${aws_s3_bucket.frontend.id}"

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
    compress               = true
  }

  # Handle SPA routing - return index.html for 404s
  custom_error_response {
    error_code         = 404
    response_code      = 200
    response_page_path = "/index.html"
  }

  custom_error_response {
    error_code         = 403
    response_code      = 200
    response_page_path = "/index.html"
  }

  restrictions {
    geo_restriction {
      restriction_type = "none"
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  tags = {
    Name = "${var.project_name}-${var.environment}-frontend-cdn"
  }
}

# --- S3 Bucket Policy for CloudFront ---
resource "aws_s3_bucket_policy" "frontend" {
  bucket = aws_s3_bucket.frontend.id

  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Sid       = "AllowCloudFrontServicePrincipal"
        Effect    = "Allow"
        Principal = {
          Service = "cloudfront.amazonaws.com"
        }
        Action   = "s3:GetObject"
        Resource = "${aws_s3_bucket.frontend.arn}/*"
        Condition = {
          StringEquals = {
            "AWS:SourceArn" = aws_cloudfront_distribution.frontend.arn
          }
        }
      }
    ]
  })
}

# --- Generate and Upload Frontend Files ---
resource "local_file" "frontend_config" {
  content = <<-EOF
// Auto-generated by Terraform
window.APP_CONFIG = {
    API_ENDPOINT: "${aws_apigatewayv2_api.frontend_api.api_endpoint}",
    S3_BUCKET: "${module.storage.training_data_bucket_id}",
    DATASTORE_ID: "${module.healthimaging.data_store_id}",
    ENVIRONMENT: "${var.environment}",
    ENABLE_DEBUG: ${var.environment == "dev" ? "true" : "false"},
    
    // AWS Region
    AWS_REGION: "${var.aws_region}",
    
    // Cognito configuration for direct HealthImaging access
    COGNITO: {
        USER_POOL_ID: "${module.cognito.user_pool_id}",
        CLIENT_ID: "${module.cognito.user_pool_client_id}",
        IDENTITY_POOL_ID: "${module.cognito.identity_pool_id}"
    },
    
    ROUTES: {
        GET_IMAGE_FRAME: "/get-image-frame",
        TRIGGER_PIPELINE: "/trigger-pipeline",
        GET_PRESIGNED_URL: "/get-url"
    }
};
console.log("App Config Loaded:", window.APP_CONFIG);
EOF
  filename = "${path.module}/../frontend/config.js"
}

# Upload index.html
resource "aws_s3_object" "frontend_index" {
  bucket       = aws_s3_bucket.frontend.id
  key          = "index.html"
  source       = "${path.module}/../frontend/index.html"
  content_type = "text/html"
  etag         = filemd5("${path.module}/../frontend/index.html")
}

# Upload config.js (depends on local_file generation)
resource "aws_s3_object" "frontend_config" {
  bucket       = aws_s3_bucket.frontend.id
  key          = "config.js"
  content      = local_file.frontend_config.content
  content_type = "application/javascript"

  depends_on = [local_file.frontend_config]
}

# --- 1. IAM Role for Frontend Lambdas ---
# We create a specific role to avoid conflicts with module roles
resource "aws_iam_role" "frontend_lambda_role" {
  name = "${var.project_name}-${var.environment}-frontend-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = { Service = "lambda.amazonaws.com" }
    }]
  })
}

resource "aws_iam_role_policy" "frontend_lambda_policy" {
  name = "${var.project_name}-${var.environment}-frontend-policy"
  role = aws_iam_role.frontend_lambda_role.id
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [
      {
        Effect = "Allow"
        Action = [
          "s3:GetObject",
          "s3:PutObject",
          "s3:ListBucket",
          "s3:HeadObject"
        ]
        Resource = [
          module.storage.training_data_bucket_arn,
          "${module.storage.training_data_bucket_arn}/*"
        ]
      },
      {
        Effect = "Allow"
        Action = [
          "medical-imaging:GetImageSet",
          "medical-imaging:GetImageFrame",
          "medical-imaging:GetImageSetMetadata",
          "medical-imaging:SearchImageSets",
          "medical-imaging:ListImageSetVersions"
        ]
        Resource = "*"
      },
      {
        Effect = "Allow"
        Action = [
          "logs:CreateLogGroup",
          "logs:CreateLogStream",
          "logs:PutLogEvents"
        ]
        Resource = "arn:aws:logs:*:*:*"
      }
    ]
  })
}

# --- 2. Lambda: Get Presigned URL (For Streaming) ---
data "archive_file" "get_presigned_url_zip" {
  type        = "zip"
  source_dir  = "${path.module}/../python/src/lambda_handlers/get_presigned_url"
  output_path = "${path.module}/lambda_zips/get_presigned_url.zip"
}

resource "aws_lambda_function" "get_presigned_url" {
  filename         = data.archive_file.get_presigned_url_zip.output_path
  function_name    = "${var.project_name}-${var.environment}-get-presigned-url"
  role             = aws_iam_role.frontend_lambda_role.arn
  handler          = "handler.lambda_handler"
  source_code_hash = data.archive_file.get_presigned_url_zip.output_base64sha256
  runtime          = "python3.11"
  timeout          = 30
  
  environment {
    variables = {
      BUCKET_NAME  = module.storage.training_data_bucket_id
      DATASTORE_ID = module.healthimaging.data_store_id
    }
  }
}

# --- 3. API Gateway (HTTP API) ---
resource "aws_apigatewayv2_api" "frontend_api" {
  name          = "${var.project_name}-${var.environment}-api"
  protocol_type = "HTTP"
  cors_configuration {
    allow_origins = ["*"]
    allow_methods = ["GET", "POST", "OPTIONS"]
    allow_headers = ["*"]
  }
}

resource "aws_apigatewayv2_stage" "default" {
  api_id      = aws_apigatewayv2_api.frontend_api.id
  name        = "$default"
  auto_deploy = true
}

# Route 1: Get Image Frame URL
resource "aws_apigatewayv2_integration" "get_url_int" {
  api_id           = aws_apigatewayv2_api.frontend_api.id
  integration_type = "AWS_PROXY"
  integration_uri  = aws_lambda_function.get_presigned_url.invoke_arn
}

resource "aws_apigatewayv2_route" "get_url_route" {
  api_id    = aws_apigatewayv2_api.frontend_api.id
  route_key = "GET /get-image-frame"
  target    = "integrations/${aws_apigatewayv2_integration.get_url_int.id}"
}

# Route 2: Trigger Pipeline (Connects to the Lambda from main-modules.tf)
resource "aws_apigatewayv2_integration" "trigger_int" {
  api_id           = aws_apigatewayv2_api.frontend_api.id
  integration_type = "AWS_PROXY"
  # References the pipeline lambda created in the modules
  integration_uri  = module.lambda_functions.pipeline_trigger_function_arn
}

resource "aws_apigatewayv2_route" "trigger_route" {
  api_id    = aws_apigatewayv2_api.frontend_api.id
  route_key = "POST /trigger-pipeline"
  target    = "integrations/${aws_apigatewayv2_integration.trigger_int.id}"
}

# --- 4. Permissions ---
resource "aws_lambda_permission" "api_gw_url" {
  statement_id  = "AllowExecutionFromAPIGateway"
  action        = "lambda:InvokeFunction"
  function_name = aws_lambda_function.get_presigned_url.function_name
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.frontend_api.execution_arn}/*/*"
}

resource "aws_lambda_permission" "api_gw_trigger" {
  statement_id  = "AllowExecutionFromAPIGatewayTrigger"
  action        = "lambda:InvokeFunction"
  function_name = module.lambda_functions.pipeline_trigger_function_arn
  principal     = "apigateway.amazonaws.com"
  source_arn    = "${aws_apigatewayv2_api.frontend_api.execution_arn}/*/*"
}

# --- 5. Output ---
output "api_gateway_endpoint" {
  description = "The API Endpoint to use in frontend/config.js"
  value       = aws_apigatewayv2_api.frontend_api.api_endpoint
}

output "frontend_url" {
  description = "CloudFront URL for the frontend application"
  value       = "https://${aws_cloudfront_distribution.frontend.domain_name}"
}

output "frontend_bucket" {
  description = "S3 bucket for frontend assets"
  value       = aws_s3_bucket.frontend.id
}

output "cloudfront_distribution_id" {
  description = "CloudFront distribution ID for cache invalidation"
  value       = aws_cloudfront_distribution.frontend.id
}
