#!/bin/bash
# ============================================================================
# Generate Frontend Configuration from Terraform Outputs
# Healthcare Imaging MLOps Platform
# ============================================================================
#
# This script reads Terraform outputs and generates a config.js file
# that the frontend can use to dynamically configure API endpoints.
#
# Usage:
#   ./scripts/generate-frontend-config.sh [environment]
#
# Example:
#   ./scripts/generate-frontend-config.sh dev
#
# ============================================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
TERRAFORM_DIR="$PROJECT_ROOT/terraform"
FRONTEND_DIR="$PROJECT_ROOT/frontend"
OUTPUT_FILE="$FRONTEND_DIR/config.js"

# Default environment
ENVIRONMENT="${1:-dev}"

echo "=============================================="
echo "Frontend Configuration Generator"
echo "=============================================="
echo "Environment: $ENVIRONMENT"
echo "Terraform Dir: $TERRAFORM_DIR"
echo "Output File: $OUTPUT_FILE"
echo ""

# Check if Terraform is available
if ! command -v terraform &> /dev/null; then
    echo "Error: terraform command not found"
    echo "Please install Terraform or ensure it's in your PATH"
    exit 1
fi

# Navigate to Terraform directory
cd "$TERRAFORM_DIR"

# Get Terraform outputs
echo "Fetching Terraform outputs..."

API_GATEWAY_URL=$(terraform output -raw api_gateway_url 2>/dev/null || echo "")
S3_BUCKET=$(terraform output -raw s3_bucket_name 2>/dev/null || echo "")

# Validate outputs
if [ -z "$API_GATEWAY_URL" ]; then
    echo "Warning: api_gateway_url output not found"
    echo "Using placeholder value. Update manually after deployment."
    API_GATEWAY_URL="https://YOUR_API_GATEWAY_URL.execute-api.us-east-1.amazonaws.com"
fi

# Generate config.js
echo "Generating $OUTPUT_FILE..."

cat > "$OUTPUT_FILE" << EOF
// ============================================================================
// Frontend Configuration
// Auto-generated by generate-frontend-config.sh
// Environment: $ENVIRONMENT
// Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
// ============================================================================

window.APP_CONFIG = {
    // API Gateway endpoint
    API_ENDPOINT: "$API_GATEWAY_URL",
    
    // S3 bucket for uploads
    S3_BUCKET: "$S3_BUCKET",
    
    // Environment
    ENVIRONMENT: "$ENVIRONMENT",
    
    // Feature flags
    ENABLE_DEBUG: $( [ "$ENVIRONMENT" = "dev" ] && echo "true" || echo "false" ),
    
    // API routes
    ROUTES: {
        GET_IMAGE_FRAME: "/get-image-frame",
        TRIGGER_PIPELINE: "/trigger-pipeline",
        GET_PRESIGNED_URL: "/get-url"
    }
};

console.log("App Config Loaded:", window.APP_CONFIG);
EOF

echo ""
echo "Configuration generated successfully!"
echo ""
echo "API Endpoint: $API_GATEWAY_URL"
echo "S3 Bucket: $S3_BUCKET"
echo ""
echo "To use this configuration, include config.js in your HTML:"
echo '  <script src="config.js"></script>'
echo ""
echo "Then access values via window.APP_CONFIG.API_ENDPOINT"
